// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerceptionComponent;

namespace PerceptionComponent.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20211117161221_Initial Schema")]
    partial class InitialSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("PerceptionComponent.ImgDB", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("blob")
                        .HasColumnType("BLOB");

                    b.Property<int>("hash")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("PerceptionComponent.ObjDescription", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cls")
                        .HasColumnType("TEXT");

                    b.Property<double>("height")
                        .HasColumnType("REAL");

                    b.Property<int?>("imageid")
                        .HasColumnType("INTEGER");

                    b.Property<double>("width")
                        .HasColumnType("REAL");

                    b.Property<double>("x")
                        .HasColumnType("REAL");

                    b.Property<double>("y")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("imageid");

                    b.ToTable("Rectangles");
                });

            modelBuilder.Entity("PerceptionComponent.ObjDescription", b =>
                {
                    b.HasOne("PerceptionComponent.ImgDB", "image")
                        .WithMany("descs")
                        .HasForeignKey("imageid");

                    b.Navigation("image");
                });

            modelBuilder.Entity("PerceptionComponent.ImgDB", b =>
                {
                    b.Navigation("descs");
                });
#pragma warning restore 612, 618
        }
    }
}
